# Generated by Django 4.0.2 on 2022-02-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_full_name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjec_name', models.CharField(blank=True, max_length=250, null=True)),
                ('subjec_description', models.CharField(blank=True, max_length=500, null=True)),
                ('prof_full_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='userAuthentication.professor')),
            ],
        ),
        migrations.CreateModel(
            name='assignmentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(blank=True, max_length=250, null=True)),
                ('assignment_file', models.FileField(upload_to='')),
                ('subject_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='userAuthentication.subjects')),
            ],
        ),
    ]
