# Generated by Django 4.0.2 on 2022-02-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subjec_description',
            new_name='subject_description',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subjec_name',
            new_name='subject_name',
        ),
    ]
