# Generated by Django 4.0.2 on 2022-02-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='prof_full_name',
        ),
        migrations.DeleteModel(
            name='assignmentFiles',
        ),
        migrations.DeleteModel(
            name='professor',
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
