# Generated by Django 4.0.2 on 2022-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0002_rename_subjec_description_subjects_subject_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfiles',
            name='assignment_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
