# Generated by Django 4.0.2 on 2022-02-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0005_alter_assignmentfiles_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfiles',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
